import type { BusinessLedgerRecord } from "../../shared/business-ledger-types";
import { BusinessLedgerError } from "./ledger-store";
const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
const money = (value: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" }).format(value / 100);
export function renderBusinessDocument(record: BusinessLedgerRecord, client: string): string {
  if ((record.kind !== "quote" && record.kind !== "invoice") || record.detail !== "complete" || !record.items?.length) throw new BusinessLedgerError("This record is a summary; its original document has not been imported.", 422);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(record.number ?? "Draft")} · ${escape(record.title)}</title><style>
  body{font:15px system-ui,sans-serif;color:#162735;margin:40px auto;max-width:800px;padding:24px}header{background:#132b3c;color:white;padding:32px;border-bottom:5px solid #22b8cf}h1{font-size:32px;margin:8px 0}h2{font-size:20px}table{width:100%;border-collapse:collapse;margin:32px 0}td,th{padding:14px 8px;border-bottom:1px solid #ddd;text-align:left}td:not(:first-child),th:not(:first-child){text-align:right}tfoot{font-weight:bold;font-size:20px}section{white-space:pre-wrap;margin:28px 0}button{padding:12px 20px;cursor:pointer;margin-bottom:20px}@media print{button{display:none}body{margin:0;max-width:none;padding:0}header{print-color-adjust:exact}tr{break-inside:avoid}@page{margin:18mm}}
  </style></head><body><button id="print">Print / save PDF</button><header><div>${escape(record.issuerName)}</div><h1>${record.kind === "quote" ? "Quote" : record.tax ? "Tax invoice" : "Invoice"}</h1><div>${escape(record.number ?? "DRAFT — not issued")}</div>${record.voided ? `<h2>VOID — ${escape(record.voided.reason)}</h2>` : ""}</header><section>${escape(record.issuerDetails?.address)}<br>${escape(record.issuerDetails?.email)}${record.tax ? `<br>VAT registration: ${escape(record.issuerDetails?.vatNumber)}` : ""}</section><h2>${escape(record.title)}</h2><section>Bill to: ${escape(record.clientName ?? client)}${record.clientAddress ? `<br>${escape(record.clientAddress)}` : ""}${record.clientVatNumber ? `<br>Client VAT: ${escape(record.clientVatNumber)}` : ""}<br>Issue date: ${escape(record.issuedOn)}<br>${record.kind === "quote" ? "Valid until" : "Due date"}: ${escape(record.dueOn)}</section><table><thead><tr><th>Description</th><th>Quantity</th><th>Rate${record.tax ? record.tax.mode === "inclusive" ? " incl. VAT" : " excl. VAT" : ""}</th><th>Amount</th></tr></thead><tbody>${record.items.map((item) => `<tr><td>${escape(item.description)}</td><td>${item.quantity}</td><td>${money(item.unitPriceMinor)}</td><td>${money(item.quantity * item.unitPriceMinor)}</td></tr>`).join("")}</tbody><tfoot>${record.tax ? `<tr><td colspan="3">Subtotal excluding VAT</td><td>${money(record.subtotalMinor ?? 0)}</td></tr><tr><td colspan="3">VAT ${record.tax.rateBps / 100}%</td><td>${money(record.vatMinor ?? 0)}</td></tr>` : ""}<tr><td colspan="3">Total ZAR</td><td>${money(record.amountMinor ?? 0)}</td></tr></tfoot></table><section>${escape(record.terms)}</section><section>${escape(record.issuerDetails?.paymentInstructions)}</section><script src="/api/business/ledger/print.js"></script></body></html>`;
}
