import fs from "node:fs/promises";
import path from "node:path";
import {
  VisualVerificationResultSchema,
  type VisualVerificationResult,
} from "../../shared/visual-verification-types";
import { jobsDir } from "../workers/job-store";

/**
 * Where screenshots and verdicts are kept.
 *
 * Beside the job record in `~/.agentos-ui`, not in the vault and not in the
 * repository: these are artefacts of one run, and a directory of PNGs is not
 * something a project should carry in its history.
 *
 * The layout is per-revision, and that is the whole point of this module:
 *
 *     jobs/<jobId>/visual/r1/designs-desktop.png
 *     jobs/<jobId>/visual/r1/verification.json
 *     jobs/<jobId>/visual/r2/…
 *
 * Revision 1 is never overwritten by revision 2. "What did it look like before
 * we sent it back, and did the revision actually fix it?" is the question this
 * step exists to answer, and it cannot be answered by a directory that only
 * ever holds the latest attempt.
 */

/** The same shape `job-store` generates, checked here because this builds paths. */
const JOB_ID = /^job_[A-Za-z0-9_-]{4,64}$/;

/** Generated by `screenshotName`, and re-checked before any file is read. */
const FILENAME = /^[a-z0-9][a-z0-9-]{0,80}\.png$/;

const VERIFICATION_FILE = "verification.json";

function assertJobId(jobId: string): void {
  if (!JOB_ID.test(jobId)) throw new Error(`Invalid job id: ${jobId}`);
}

function assertRevision(revision: number): void {
  if (!Number.isInteger(revision) || revision < 1 || revision > 9_999) {
    throw new Error(`Invalid revision: ${revision}`);
  }
}

/** Everything one job's visual verification has ever produced. */
export function jobVisualDir(jobId: string): string {
  assertJobId(jobId);
  return path.join(jobsDir(), jobId, "visual");
}

/** One attempt's screenshots and verdict. */
export function revisionDir(jobId: string, revision: number): string {
  assertRevision(revision);
  return path.join(jobVisualDir(jobId), `r${revision}`);
}

/**
 * A stable, readable name for one capture.
 *
 * `/designs` at `desktop` becomes `designs-desktop.png`; the site root becomes
 * `root-desktop.png`. Readable because an operator will see these filenames in
 * a directory long after the console that made them has moved on.
 */
export function screenshotName(route: string, viewport: string): string {
  const slug = (value: string) =>
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");

  return `${slug(route) || "root"}-${slug(viewport) || "viewport"}.png`;
}

/**
 * Resolves one screenshot, refusing anything that escapes its revision.
 *
 * The console asks for screenshots by name, so this is a boundary: a name that
 * is not one `screenshotName` would have produced is refused rather than
 * resolved, and the result is checked against the directory it must be under.
 */
export function resolveScreenshot(
  jobId: string,
  revision: number,
  filename: string,
): string {
  if (!FILENAME.test(filename)) {
    throw new Error(`Invalid screenshot name: ${filename}`);
  }

  const directory = revisionDir(jobId, revision);
  const full = path.resolve(directory, filename);

  if (!full.startsWith(path.resolve(directory) + path.sep)) {
    throw new Error("Invalid screenshot path");
  }

  return full;
}

/** Writes one capture, and returns the name the result should record. */
export async function saveScreenshot(
  jobId: string,
  revision: number,
  filename: string,
  data: Buffer,
): Promise<string> {
  const target = resolveScreenshot(jobId, revision, filename);

  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, data);

  return filename;
}

/**
 * Writes a verdict atomically.
 *
 * Via a temp file and a rename, like every other record in this system: a
 * half-written verdict would be worse than no verdict, because it would be
 * read as one.
 */
export async function saveVerification(
  result: VisualVerificationResult,
): Promise<void> {
  const directory = revisionDir(result.jobId, result.revision);
  await fs.mkdir(directory, { recursive: true });

  const target = path.join(directory, VERIFICATION_FILE);
  const temporary = `${target}.${process.pid}.tmp`;

  await fs.writeFile(temporary, `${JSON.stringify(result, null, 2)}\n`, "utf8");
  await fs.rename(temporary, target);
}

/** One revision's verdict, or `undefined` when it was never verified. */
export async function readVerification(
  jobId: string,
  revision: number,
): Promise<VisualVerificationResult | undefined> {
  try {
    const contents = await fs.readFile(
      path.join(revisionDir(jobId, revision), VERIFICATION_FILE),
      "utf8",
    );

    const parsed = VisualVerificationResultSchema.safeParse(
      JSON.parse(contents) as unknown,
    );

    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Every verification this job has, oldest first.
 *
 * An unreadable revision is skipped rather than failing the listing — the
 * point of keeping history is that the rest of it survives one bad file.
 */
export async function readVerificationHistory(
  jobId: string,
): Promise<VisualVerificationResult[]> {
  let entries: string[];

  try {
    entries = await fs.readdir(jobVisualDir(jobId));
  } catch {
    return [];
  }

  const revisions = entries
    .map((entry) => /^r(\d{1,4})$/.exec(entry)?.[1])
    .filter((match): match is string => match !== undefined)
    .map(Number)
    .sort((a, b) => a - b);

  const results = await Promise.all(
    revisions.map((revision) => readVerification(jobId, revision)),
  );

  return results.filter(
    (result): result is VisualVerificationResult => result !== undefined,
  );
}
