import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

/**
 * Where images actually live.
 *
 * Deliberately outside `~/AgentOS`: the vault is a human-owned, git-tracked
 * knowledge layer, and filling it with PNGs would turn every design reference
 * into repository history. Media is its own layer, stored by id, and reached
 * only through the adapter — the browser never learns a filesystem path.
 */

const execFileAsync = promisify(execFile);

export function mediaRoot(): string {
  return (
    process.env.AGENTOS_MEDIA_DIR ?? path.join(os.homedir(), "AgentOS-Media")
  );
}

export const ORIGINALS = "originals";
export const THUMBNAILS = "thumbnails";
export const GENERATED = "generated";

/** The formats the library accepts, and the extension each is stored under. */
const EXTENSION_BY_TYPE: Record<string, string> = {
  "image/png": ".png",
  "image/jpeg": ".jpg",
  "image/webp": ".webp",
  "image/gif": ".gif",
  "image/avif": ".avif",
  "image/svg+xml": ".svg",
  "video/mp4": ".mp4",
  "video/quicktime": ".mov",
  "video/webm": ".webm",
};

/** A stored name or a bare extension (`.mp4`) — `path.extname` returns nothing for the latter. */
export function isVideoName(nameOrExtension: string): boolean {
  return /\.(mp4|mov|webm)$/i.test(nameOrExtension);
}

/**
 * The name a file's thumbnail is stored under.
 *
 * An image's thumbnail is a smaller copy in the same format. A video's is a
 * poster frame, so it is a JPEG whatever the video is — which is also what
 * lets every `<img src={thumbnailUrl}>` in the app show a video without
 * knowing it is one.
 */
export function thumbnailNameFor(storedName: string): string {
  return isVideoName(storedName)
    ? `${path.basename(storedName, path.extname(storedName))}.jpg`
    : storedName;
}

export function extensionFor(contentType: string): string | undefined {
  return EXTENSION_BY_TYPE[contentType.split(";")[0].trim().toLowerCase()];
}

const TYPE_BY_EXTENSION = new Map(
  Object.entries(EXTENSION_BY_TYPE).map(([type, extension]) => [extension, type]),
);

export function contentTypeFor(storedName: string): string {
  return TYPE_BY_EXTENSION.get(path.extname(storedName).toLowerCase()) ?? "application/octet-stream";
}

/**
 * Resolves a stored file, refusing anything that escapes the media root.
 *
 * Stored names are generated by this module, never supplied by a caller — but
 * this is the boundary, so it is checked here rather than trusted upstream.
 */
export function resolveMedia(folder: string, storedName: string): string {
  const root = path.resolve(mediaRoot());
  const full = path.resolve(root, folder, storedName);

  if (!full.startsWith(root + path.sep)) {
    throw new Error("Invalid media path");
  }

  return full;
}

async function ensureDirectories(): Promise<void> {
  const root = mediaRoot();

  await Promise.all(
    [ORIGINALS, THUMBNAILS, GENERATED].map((folder) =>
      fs.mkdir(path.join(root, folder), { recursive: true }),
    ),
  );
}

export interface Dimensions {
  width: number;
  height: number;
}

/**
 * Pixel dimensions, read from the file's own header.
 *
 * The grid lays tiles out by aspect ratio before any image has loaded, so it
 * needs this at upload time. Done by hand rather than with an image library:
 * four container formats, a few dozen bytes each, and no native dependency to
 * install or keep working.
 */
export function readDimensions(data: Buffer): Dimensions | undefined {
  // PNG: an IHDR chunk at a fixed offset.
  if (data.length > 24 && data.readUInt32BE(0) === 0x89504e47) {
    return { width: data.readUInt32BE(16), height: data.readUInt32BE(20) };
  }

  // GIF: a fixed little-endian logical screen descriptor.
  if (data.length > 10 && data.toString("ascii", 0, 3) === "GIF") {
    return { width: data.readUInt16LE(6), height: data.readUInt16LE(8) };
  }

  if (data.length > 30 && data.toString("ascii", 0, 4) === "RIFF") {
    return readWebpDimensions(data);
  }

  if (data.length > 4 && data.readUInt16BE(0) === 0xffd8) {
    return readJpegDimensions(data);
  }

  return undefined;
}

/** WebP has three sub-formats, each storing its size differently. */
function readWebpDimensions(data: Buffer): Dimensions | undefined {
  if (data.toString("ascii", 8, 12) !== "WEBP") return undefined;

  const format = data.toString("ascii", 12, 16);

  if (format === "VP8X") {
    // Two 24-bit little-endian values, each stored as size - 1.
    return {
      width: 1 + (data.readUInt16LE(24) | (data[26] << 16)),
      height: 1 + (data.readUInt16LE(27) | (data[29] << 16)),
    };
  }

  if (format === "VP8 ") {
    return {
      width: data.readUInt16LE(26) & 0x3fff,
      height: data.readUInt16LE(28) & 0x3fff,
    };
  }

  if (format === "VP8L") {
    const bits = data.readUInt32LE(21);
    return {
      width: 1 + (bits & 0x3fff),
      height: 1 + ((bits >> 14) & 0x3fff),
    };
  }

  return undefined;
}

/** JPEG stores its size in a start-of-frame marker, found by walking segments. */
function readJpegDimensions(data: Buffer): Dimensions | undefined {
  let offset = 2;

  while (offset + 9 < data.length) {
    if (data[offset] !== 0xff) {
      offset += 1;
      continue;
    }

    const marker = data[offset + 1];

    // SOF0-SOF15, excluding the four markers in that range that are not frames.
    if (
      marker >= 0xc0 &&
      marker <= 0xcf &&
      marker !== 0xc4 &&
      marker !== 0xc8 &&
      marker !== 0xcc
    ) {
      return {
        height: data.readUInt16BE(offset + 5),
        width: data.readUInt16BE(offset + 7),
      };
    }

    // Markers without a payload carry no length to skip.
    if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd9)) {
      offset += 2;
      continue;
    }

    offset += 2 + data.readUInt16BE(offset + 2);
  }

  return undefined;
}

/** The longest edge a thumbnail is reduced to. */
const THUMBNAIL_SIZE = 800;

/**
 * Writes a smaller rendition beside the original.
 *
 * Uses macOS' own `sips`, so no image library has to be installed or kept
 * working. Failure is not an error: a library without thumbnails still works —
 * the asset simply serves its original — so this never fails an upload.
 */
async function writeThumbnail(
  storedName: string,
  dimensions: Dimensions | undefined,
): Promise<boolean> {
  // Nothing to gain from shrinking an image that is already small, or a vector.
  if (storedName.endsWith(".svg")) return false;
  if (dimensions && Math.max(dimensions.width, dimensions.height) <= THUMBNAIL_SIZE) {
    return false;
  }

  try {
    await execFileAsync(
      "sips",
      [
        "-Z",
        String(THUMBNAIL_SIZE),
        resolveMedia(ORIGINALS, storedName),
        "--out",
        resolveMedia(THUMBNAILS, storedName),
      ],
      { timeout: 15_000 },
    );

    return true;
  } catch {
    return false;
  }
}

export interface StoredMedia {
  storedName: string;
  hasThumbnail: boolean;
  dimensions?: Dimensions;
}

/**
 * Stores one image and returns what was written.
 *
 * The stored name is derived from the asset id, never from the uploaded
 * filename — so a name like `../../.ssh/id_rsa` is simply not a name that can
 * reach the filesystem.
 */
export async function storeImage(
  id: string,
  extension: string,
  data: Buffer,
): Promise<StoredMedia> {
  await ensureDirectories();

  const storedName = `${id}${extension}`;
  await fs.writeFile(resolveMedia(ORIGINALS, storedName), data);

  const dimensions = readDimensions(data);

  return {
    storedName,
    hasThumbnail: await writeThumbnail(storedName, dimensions),
    dimensions,
  };
}

export interface StoredVideo extends StoredMedia {
  durationSec?: number;
}

function ffmpegBinary(name: "ffmpeg" | "ffprobe"): string {
  return process.env[name === "ffmpeg" ? "AGENTOS_FFMPEG_BIN" : "AGENTOS_FFPROBE_BIN"]?.trim() || name;
}

export interface VideoProbe {
  width?: number;
  height?: number;
  durationSec?: number;
  codec?: string;
  pixelFormat?: string;
  hasAudio: boolean;
}

/** What ffprobe says about a video, or `undefined` when it is not one it can read. */
export async function probeVideo(file: string): Promise<VideoProbe | undefined> {
  try {
    const { stdout } = await execFileAsync(
      ffmpegBinary("ffprobe"),
      ["-v", "error", "-show_entries", "stream=codec_type,codec_name,width,height,pix_fmt:format=duration", "-of", "json", file],
      { timeout: 20_000 },
    );
    const parsed = JSON.parse(stdout) as {
      streams?: { codec_type?: string; codec_name?: string; width?: number; height?: number; pix_fmt?: string }[];
      format?: { duration?: string };
    };
    const video = parsed.streams?.find((stream) => stream.codec_type === "video");
    if (!video) return undefined;

    const duration = Number(parsed.format?.duration);

    return {
      width: video.width,
      height: video.height,
      durationSec: Number.isFinite(duration) ? Math.round(duration * 100) / 100 : undefined,
      codec: video.codec_name,
      pixelFormat: video.pix_fmt,
      hasAudio: parsed.streams?.some((stream) => stream.codec_type === "audio") ?? false,
    };
  } catch {
    return undefined;
  }
}

/**
 * A poster frame, a third of the way in.
 *
 * Not the first frame: films open on black or on a word still arriving, and a
 * tile of black rectangles tells nobody what anything is. Like image
 * thumbnails, failure is not an error — the tile falls back to the video.
 */
async function writePoster(storedName: string, durationSec: number | undefined): Promise<boolean> {
  const at = durationSec ? Math.min(durationSec * 0.35, Math.max(0, durationSec - 0.1)) : 0;

  try {
    await execFileAsync(
      ffmpegBinary("ffmpeg"),
      [
        "-y", "-loglevel", "error",
        "-ss", at.toFixed(2),
        "-i", resolveMedia(ORIGINALS, storedName),
        "-frames:v", "1",
        "-vf", `scale='min(${THUMBNAIL_SIZE},iw)':-2`,
        "-q:v", "3",
        resolveMedia(THUMBNAILS, thumbnailNameFor(storedName)),
      ],
      { timeout: 30_000 },
    );

    return true;
  } catch {
    return false;
  }
}

/**
 * Stores one video, from memory or by copying a file already on disk.
 *
 * A render of a few hundred megabytes is copied rather than read into memory
 * first. The stored name is still `<id><ext>` whatever the source was called.
 */
export async function storeVideo(
  id: string,
  extension: string,
  source: Buffer | { path: string },
): Promise<StoredVideo> {
  await ensureDirectories();

  const storedName = `${id}${extension}`;
  const target = resolveMedia(ORIGINALS, storedName);

  if (Buffer.isBuffer(source)) await fs.writeFile(target, source);
  else await fs.copyFile(source.path, target);

  const probe = await probeVideo(target);

  return {
    storedName,
    dimensions: probe?.width && probe.height ? { width: probe.width, height: probe.height } : undefined,
    durationSec: probe?.durationSec,
    hasThumbnail: await writePoster(storedName, probe?.durationSec),
  };
}

/** Removes an asset's files. A file already gone is not an error. */
export async function deleteImage(storedName: string): Promise<void> {
  await Promise.all(
    [
      [ORIGINALS, storedName],
      [THUMBNAILS, thumbnailNameFor(storedName)],
    ].map(async ([folder, name]) => {
      try {
        await fs.unlink(resolveMedia(folder, name));
      } catch {
        // Already gone, which is the state we wanted.
      }
    }),
  );
}

/** Reads a stored file, or `undefined` when it is not there. */
export async function readImage(
  folder: string,
  storedName: string,
): Promise<Buffer | undefined> {
  try {
    return await fs.readFile(resolveMedia(folder, storedName));
  } catch {
    return undefined;
  }
}
