import { useState, type FormEvent } from "react";
import { businessRecordLabel, type BusinessLedgerRecord, type BusinessProfile } from "@shared/business-ledger-types";
import { calculateBusinessTotals } from "@shared/business-billing-calculations";
import { PAPER_INPUT, PaperButton } from "@/components/paper";
import { Field } from "./business-billing-fields";
import { money, today, minor } from "./business-billing-format";
import type { Kind } from "./business-billing";

export function RecordEditor({ kind, record, entityId, entityName, profile, records, busy, onSave, onCancel, onError }: { kind: Kind; record?: BusinessLedgerRecord; entityId: string; entityName: string; profile?: BusinessProfile; records: BusinessLedgerRecord[]; busy: boolean; onSave: (record: unknown) => void; onCancel: () => void; onError: (message: string) => void }) {
  const [newRecordId] = useState(() => crypto.randomUUID());
  const document = record?.kind === "quote" || record?.kind === "invoice" ? record : undefined;
  const [items, setItems] = useState(document?.items?.map((item) => ({ description: item.description, quantity: String(item.quantity), price: String(item.unitPriceMinor / 100) })) ?? [{ description: "", quantity: "1", price: "" }]);
  const existingTax = record && "tax" in record ? record.tax : undefined;
  const initialTax = record ? existingTax : profile?.vatEnabled ? profile.vat : undefined;
  const [taxEnabled, setTaxEnabled] = useState(Boolean(initialTax));
  const [rate, setRate] = useState(String((initialTax?.rateBps ?? profile?.vat.rateBps ?? 1500) / 100));
  const [taxMode, setTaxMode] = useState<"exclusive" | "inclusive">(initialTax?.mode ?? profile?.vat.mode ?? "exclusive");
  const taxValue = () => taxEnabled ? { rateBps: minor(rate), mode: taxMode } : undefined;
  let previewTotal: string;
  try { previewTotal = money(calculateBusinessTotals(items.map((item) => ({ quantity: Number(item.quantity), unitPriceMinor: minor(item.price || "0") })), taxValue()).amountMinor); }
  catch { previewTotal = "Complete the line items"; }
  const [clientId, setClientId] = useState(record && "clientId" in record ? record.clientId ?? "" : "");
  const field = (label: string, name: string, value?: string | number, type = "text", required = true) => <Field label={label}><input name={name} className={PAPER_INPUT} type={type} defaultValue={value} required={required} step={type === "number" ? "0.01" : undefined} min={type === "number" ? "0" : undefined} /></Field>;
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    try {
      const form = new FormData(event.currentTarget);
      const get = (name: string) => String(form.get(name) ?? "").trim();
      const id = record?.id ?? newRecordId;
      const base = { ...record, id, entityId, kind, source: record?.source ?? "agentos", sourceId: record?.sourceId ?? id };
      if (kind === "client") onSave({ ...base, name: get("name"), companyName: get("company") || undefined, email: get("email") || undefined, address: get("address") || undefined, vatNumber: get("vatNumber") || undefined });
      else if (kind === "quote" || kind === "invoice") onSave({ ...base, title: get("title"), clientId, currency: "ZAR", detail: "complete", status: "draft", issuedOn: get("issuedOn"), dueOn: get("dueOn"), terms: get("terms"), tax: taxValue(), issuerName: get("issuerName"), items: items.map((item) => ({ description: item.description.trim(), quantity: Number(item.quantity), unitPriceMinor: minor(item.price) })) });
      else if (kind === "service") onSave({ ...base, title: get("title"), clientId: clientId || undefined, currency: "ZAR", amountMinor: get("amount") ? minor(form.get("amount")) : undefined, cadence: get("cadence"), state: get("state"), tax: taxValue(), nextInvoiceDate: get("nextInvoiceDate") || undefined });
      else if (kind === "project") onSave({ ...base, title: get("title"), clientId: clientId || undefined, status: get("status") || undefined, currency: "ZAR", amountMinor: get("amount") ? minor(form.get("amount")) : undefined });
      else if (kind === "expense") onSave({ ...base, vendor: get("vendor"), category: get("category"), currency: "ZAR", amountMinor: minor(form.get("amount")), paidOn: get("date"), reference: get("reference") });
      else { const amountMinor = minor(form.get("amount")); onSave({ ...base, clientId, currency: "ZAR", amountMinor, receivedOn: get("date"), reference: get("reference"), allocations: get("invoice") ? [{ invoiceId: get("invoice"), amountMinor }] : [] }); }
    } catch (error) { onError(error instanceof Error ? error.message : "Check the entered values."); }
  }
  return <form onSubmit={submit} className="mb-6 grid gap-4 border border-paper-mist bg-paper-cream p-5"><h3 className="font-semibold">{record ? "Edit" : "New"} {kind}</h3><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2">
    {kind === "client" ? <>{field("Contact name", "name", record?.kind === "client" ? record.name : "")}{field("Company", "company", record?.kind === "client" ? record.companyName : "", "text", false)}{field("Email", "email", record?.kind === "client" ? record.email : "", "email", false)}{field("Billing address", "address", record?.kind === "client" ? record.address : "", "text", false)}{field("Client VAT number (if registered)", "vatNumber", record?.kind === "client" ? record.vatNumber : "", "text", false)}</> : null}
    {["project", "quote", "invoice", "service", "payment"].includes(kind) ? <Field label="Client"><select className={PAPER_INPUT} required={kind !== "service" && kind !== "project"} value={clientId} onChange={(event) => setClientId(event.target.value)}><option value="">Choose client</option>{records.filter((row) => row.kind === "client").map((row) => <option key={row.id} value={row.id}>{businessRecordLabel(row)}</option>)}</select></Field> : null}
    {["project", "quote", "invoice", "service"].includes(kind) ? field(kind === "project" ? "Project name" : "Title", "title", record && "title" in record ? record.title : "") : null}
    {kind === "quote" || kind === "invoice" ? <>{field("Business / issuer name", "issuerName", document?.issuerName ?? profile?.legalName ?? entityName)}{field("Issue date", "issuedOn", document?.issuedOn ?? today(), "date")}{field(kind === "quote" ? "Valid until" : "Due date", "dueOn", document?.dueOn, "date")}<div className="grid gap-3 sm:col-span-2"><h4 className="text-sm font-semibold">Line items · ZAR</h4>{items.map((item, index) => <div key={index} className="grid gap-2 sm:grid-cols-[2fr_1fr_1fr_auto]">{(["description", "quantity", "price"] as const).map((key) => <Field key={key} label={`${key === "price" ? "Rate (R)" : key === "quantity" ? "Quantity" : "Description"} ${index + 1}`}><input className={PAPER_INPUT} required type={key === "description" ? "text" : "number"} min={key === "quantity" ? 1 : 0} step={key === "quantity" ? 1 : "0.01"} value={item[key]} onChange={(event) => setItems(items.map((row, i) => i === index ? { ...row, [key]: event.target.value } : row))} /></Field>)}<PaperButton type="button" disabled={items.length === 1} onClick={() => setItems(items.filter((_, i) => i !== index))}>Remove</PaperButton></div>)}<PaperButton type="button" disabled={items.length >= 100} onClick={() => setItems([...items, { description: "", quantity: "1", price: "" }])}>Add line item</PaperButton><p className="text-right font-semibold">Total: {previewTotal}</p><Field label="Terms / payment instructions"><textarea name="terms" className={PAPER_INPUT} rows={3} defaultValue={document?.terms ?? profile?.defaultTerms ?? "Payment due by the due date."} /></Field><p className="text-xs text-paper-sage">VAT uses the selected rate and price basis, rounded once per document. Issuing locks the document and its business details.</p></div></> : null}
    {["quote", "invoice", "service"].includes(kind) ? <div className="grid gap-3 sm:col-span-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={taxEnabled} disabled={!profile?.vatEnabled && !existingTax} onChange={(event) => setTaxEnabled(event.target.checked)} />Apply VAT</label>{!profile?.vatEnabled ? <p className="text-xs text-paper-sage">Configure your VAT registration in Business details below before enabling VAT.</p> : null}{taxEnabled ? <div className="grid gap-3 sm:grid-cols-2"><Field label="VAT rate (%)"><input type="number" min="0" max="100" step="0.01" required className={PAPER_INPUT} value={rate} onChange={(event) => setRate(event.target.value)} /></Field><Field label="Prices"><select className={PAPER_INPUT} value={taxMode} onChange={(event) => setTaxMode(event.target.value as "exclusive" | "inclusive")}><option value="exclusive">Exclude VAT — add VAT</option><option value="inclusive">Include VAT — extract VAT</option></select></Field></div> : null}</div> : null}
    {kind === "service" ? <><Field label="Service state"><select name="state" className={PAPER_INPUT} defaultValue={record?.kind === "service" ? record.state : "needs_setup"}>{["needs_setup", "active", "paused", "cancelled"].map((state) => <option key={state}>{state}</option>)}</select></Field><Field label="Billing frequency"><select name="cadence" className={PAPER_INPUT} defaultValue={record?.kind === "service" ? record.cadence : "monthly"}>{["monthly", "quarterly", "semiannual", "annual", "ad-hoc"].map((cadence) => <option key={cadence}>{cadence}</option>)}</select></Field>{field("Next invoice date", "nextInvoiceDate", record?.kind === "service" ? record.nextInvoiceDate : "", "date", false)}</> : null}
    {["project", "service", "expense", "payment"].includes(kind) ? field(kind === "project" ? "Project value (R, optional)" : "Amount (R)", "amount", record && "amountMinor" in record && record.amountMinor !== undefined ? record.amountMinor / 100 : "", "number", kind !== "service" && kind !== "project") : null}
    {kind === "project" ? <Field label="Status"><select name="status" className={PAPER_INPUT} defaultValue={record?.kind === "project" ? record.status ?? "planning" : "planning"}>{["planning", "active", "on-hold", "completed", "cancelled"].map((status) => <option key={status}>{status}</option>)}{record?.kind === "project" && record.status && !["planning", "active", "on-hold", "completed", "cancelled"].includes(record.status) ? <option>{record.status}</option> : null}</select></Field> : null}
    {kind === "expense" ? <>{field("Vendor", "vendor")}{field("Category", "category")}</> : null}
    {kind === "payment" ? <Field label="Allocate to invoice"><select name="invoice" key={clientId} className={PAPER_INPUT}><option value="">Unallocated client credit</option>{records.filter((row) => row.kind === "invoice" && row.status === "issued" && !row.voided && row.clientId === clientId).map((row) => <option key={row.id} value={row.id}>{"number" in row ? row.number : ""} · {businessRecordLabel(row)}</option>)}</select></Field> : null}
    {kind === "expense" || kind === "payment" ? <>{field(kind === "payment" ? "Received on" : "Paid on", "date", today(), "date")}{field("Reference / note", "reference", "", "text", false)}<p className="text-xs text-paper-sage sm:col-span-2">Record actual transactions only. Saved payments and expenses preserve financial history and can be voided with a reason if entered incorrectly.</p></> : null}
  </fieldset><div className="flex gap-3"><PaperButton type="submit" variant="amber" disabled={busy}>{busy ? "Saving…" : "Save"}</PaperButton><PaperButton type="button" disabled={busy} onClick={onCancel}>Cancel</PaperButton></div></form>;
}
